/*
 * 	file: CardReaderStandard.h
 *  Trabajo Práctico 1 - Interrupciones
 *  GRUPO 5 - Laboratorio de Microprocesadores
 */

#ifndef CARDREADERSTANDARD_H_
#define CARDREADERSTANDARD_H_

/******************************************************************************
 *							  DEFINICIONES
 ******************************************************************************/

#define TRACK_NUM 3

#define PAR 0
#define IMPAR 1

#define PARITY_TRACK1 IMPAR
#define PARITY_TRACK2 IMPAR
#define PARITY_TRACK3 IMPAR

#define DATA_OFFSET_ASCII_TRACK1 32
#define DATA_OFFSET_ASCII_TRACK2 48
#define DATA_OFFSET_ASCII_TRACK3 DATA_OFFSET_ASCII_TRACK2

#define CHARS_NUM_TRACK1 79
#define CHARS_NUM_TRACK2 40
#define CHARS_NUM_TRACK3 107

#define CHAR_SIZE_TRACK1 7
#define CHAR_SIZE_TRACK2 5
#define CHAR_SIZE_TRACK3 5

#define BITS_TRACK1 (CHARS_NUM_TRACK1 * CHAR_SIZE_TRACK1)
#define BITS_TRACK2 (CHARS_NUM_TRACK2 * CHAR_SIZE_TRACK2)
#define BITS_TRACK3 (CHARS_NUM_TRACK3 * CHAR_SIZE_TRACK3)

//Defino track 1 y 3 para ser coherente

//track1
#define START_SENTINEL_TRACK1 '%' - DATA_OFFSET_ASCII_TRACK1 //000101
#define FIELD_SEPARATOR_TRACK1 '^' - DATA_OFFSET_ASCII_TRACK1 //111110
#define END_SENTINEL_TRACK1 '?' - DATA_OFFSET_ASCII_TRACK1  //011111
#define MIN_VALUE_TRACK1 '0' - DATA_OFFSET_ASCII_TRACK1
#define MAX_VALUE_TRACK1 'Z' - DATA_OFFSET_ASCII_TRACK1
#define N_OF_FIELDS_SEPARATORS_TRACK1 2
#define N_OF_FORMAT_CODE_TRACK1 1

//track2
#define START_SENTINEL_TRACK2 ';' - DATA_OFFSET_ASCII_TRACK2 //1011
#define FIELD_SEPARATOR_TRACK2 '=' - DATA_OFFSET_ASCII_TRACK2 //1101
#define END_SENTINEL_TRACK2 '?' - DATA_OFFSET_ASCII_TRACK2  //1111
#define MIN_VALUE_TRACK2 '0' - DATA_OFFSET_ASCII_TRACK2
#define MAX_VALUE_TRACK2 'Z' - DATA_OFFSET_ASCII_TRACK2
#define N_OF_FIELDS_SEPARATORS_TRACK2 1
#define N_OF_FORMAT_CODE_TRACK2 0

//track3
#define START_SENTINEL_TRACK3 START_SENTINEL_TRACK2
#define FIELD_SEPARATOR_TRACK3 FIELD_SEPARATOR_TRACK2
#define END_SENTINEL_TRACK3 END_SENTINEL_TRACK2
#define MIN_VALUE_TRACK3 MIN_VALUE_TRACK2
#define MAX_VALUE_TRACK3 MAX_VALUE_TRACK2
#define N_OF_FIELDS_SEPARATORS_TRACK3 N_OF_FIELDS_SEPARATORS_TRACK2
#define N_OF_FORMAT_CODE_TRACK3 2


#endif /* CARDREADERSTANDARD_H_ */
